name: 'Buildnote GitHub Action'
description: 'Action wrapping Buildnote CLI'
author: 'Buildnote'
branding:
  icon: 'code'
  color: 'gray-dark'
inputs:
  version:
    description: 'Version of Buildnote cli to use'
    required: false
    default: '0.0.4'
  module:
    description: 'Module to upload results for'
    required: false
    default: '-'
  command:
    description: 'Buildnote command to execute'
    required: false
    default: "test-results"
  installOnly:
    description: 'Install buildnote without running command'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
