name: 'Buildnote Action'
description: 'Action wrapping Buildnote CLI'
author: 'Buildnote'
branding:
  icon: 'code'
  color: 'purple'
inputs:
  version:
    description: 'Version of Buildnote CLI to use'
    required: false
    default: '1.0.0'
  command:
    description: 'Buildnote command to execute'
    required: false
    default: "collect"
  args:
    description: 'Additional command arguments'
    required: false
  verbose:
    description: 'Runs buildnote CLI in verbose mode'
    required: false
    default: 'false'
  installOnly:
    description: 'Install buildnote without running command'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
