name: 'Buildnote GitHub Action'
description: 'Action wrapping Buildnote CLI'
author: 'Buildnote'
branding:
  icon: 'code'
  color: 'gray-dark'
inputs:
  include:
    description: 'Glob patterns of test results files to include'
    required: false
    default: "**/TEST-*.xml"
  exclude:
    description: 'Glob patterns of files and directories to exclude'
    required: false
    default: "-"
  display:
    description: 'Which tests to display'
    required: false
    default: >
      passed
      failed 
      skipped
  output:
    description: 'Path for test report output file'
    required: false
    default: ${{ env.GITHUB_STEP_SUMMARY }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--include ${{ inputs.include }}"
    - "--exclude ${{ inputs.exclude }}"
    - "--display ${{ inputs.display }}"
    - "--output ${{ inputs.output }}"

