name: 'Buildnote GitHub Action'
description: 'Action wrapping Buildnote CLI'
author: 'Buildnote'
branding:
  icon: 'code'
  color: 'gray-dark'
inputs:
  version:
    description: 'Version of Buildnote cli to use'
    required: false
    default: '0.0.3'
  include:
    description: 'Glob patterns of test results files to include'
    required: false
    default: '**/TEST-*.xml'
  exclude:
    description: 'Glob patterns of files and directories to exclude'
    required: false
    default: ''
  display:
    description: 'Which tests to display'
    required: false
    default: >
      passed
      failed
      skipped
  output:
    description: 'Path for test report output file'
    required: false
    default: ''
  upload:
    description: 'Upload results to buildnote.io'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
