name: 'Buildnote GitHub Action'
description: 'Action wrapping Buildnote CLI'
author: 'Buildnote'
branding:
  icon: 'code'
  color: 'gray-dark'
inputs:
  version:
    description: 'Version of Buildnote cli to use'
    required: false
    default: '0.0.4'
  command:
    description: 'Buildnote collect commands to execute'
    required: false
  display:
    description: 'Which tests to display'
    required: false
    default: 'passed, failed, skipped'
  output:
    description: 'Path for test report output file'
    required: false
  upload:
    description: 'Upload results to buildnote.io'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
