name: 'Buildnote Action'
description: 'Action wrapping Buildnote CLI'
author: 'Buildnote'
branding:
  icon: 'code'
  color: 'purple'
inputs:
  version:
    description: 'Version of Buildnote cli to use'
    required: false
    default: '0.0.12'
  command:
    description: 'Buildnote command to execute (report, collect, version)'
    required: false
    default: "collect"
  args:
    description: 'Additional command arguments'
    required: false
  output:
    description: 'Path for test report output file'
    required: false
  collectOnly:
    description: 'Collect events only without downloading the summary'
    required: false
    default: 'false'
  installOnly:
    description: 'Install buildnote without running command'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
